import Navbar from "@/components/shared/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import SideNav from "@/components/shared/SideNav";
import img1 from "@/assets/images/food-network 1.png";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          href="http://t1.gstatic.com/licensed-image?q=tbn:ANd9GcRq1mQLx2tcZ4owspN_OxqcHZBIc0f1F6NfiqBYgGnwEkdc3tbUGKETWmBH2PNppLs-dJJAt92vs2I16Eno7ks"
          sizes="any"
        />
      </Head>

      <body className={inter.className}>
        <main className="container mx-auto">
          <Navbar />
          <div className="my-1 flex ">
            <div className=" hidden xl:block  w-8">
              <SideNav />
            </div>
            <div className="flex-1  ">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
