import Navbar from "@/components/shared/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import SideNav from "@/components/shared/SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container mx-auto">
          <Navbar />
          <div className="my-1 flex ">
            <div className=" hidden xl:block  w-8">
              <SideNav />
            </div>
            <div className="flex-1  ">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
